### ISSUE TITLE
[QoL] Unintelligible text 

### ISSUE THREAD

**Issue by gerelef** [mdrosiadis/frontend-notes#1]
file [frontend-notes](https://github.com/mdrosiadis/frontend-notes)/[lesson1](https://github.com/mdrosiadis/frontend-notes/tree/main/lesson1)/[index.html](https://github.com/mdrosiadis/frontend-notes/blob/main/lesson1/index.html) contains unintelligible text.

**Comment by xarDeves** [comment]
Just stumbled upon the same issue myself..
It seems like the repo's author has been avoiding to provide a solution.
Any updates on the matter would be greatly appreciated

**Comment by gerelef** [comment]
> Just stumbled upon the same issue myself.. It seems like the repo's author has been avoiding to provide a solution. Any updates on the matter would be greatly appreciated

Any chance for a good alternative to this repo? I have been looking forward to using a better tool for this job.

**Comment by xarDeves** [comment]
Seems unlikely.
To put it simply, this library is one of a kind.

**Comment by mdrosiadis** [comment]
This text is black magic, cant remove

**Comment by gerelef** [comment]
> This text is black magic, cant remove

Duplicate of #1
